---
title: 异常
date: 2022-07-20 17:17:30
permalink: /pages/e93fd0/
categories:
  - 《Java教程》笔记
  - 面向对象(下)
tags:
  - 
author: 
  name: 杨洲
  link: https://github.com/xugaoyi
---

# 异常

## 一、异常简介

**Java 中的异常又称为例外，是一个在程序执行期间发生的事件，它中断正在执行程序的正常指令流**为了能够及时有效地处理程序中的运行错误，必须使用异常类，这可以让程序具有极好的容错性且更加健壮。

## 二、异常产生的原因及使用原则

在Java中一个异常的产生，主要有如下三种原因：

1. Java内部错误发生异常，Java虚拟机产生的异常。
2. 编写的程序代码中的错误所产生的异常，**例如空指针异常、数组越界异常等**。这种异常成为未检查的异常，一般需要在某些类中集中处理这些异常。
3. 通过**throw语句**手动生成的异常，这种异常称为检查的异常，一般用来告知该方法的调用者一些必要的信息。

Java通过面向对象的方法来处理异常。在一个方法的运行过程中，如果发生了异常，则这个方法会产生代表该异常的一个对象，并把它交给运行时的系统，运行时系统寻找相应的代码来处理这一异常。

**我们把生成异常对象，并把它交给运行时系统的过程称为**`抛出（throw）异常`。**运行时系统在方法的调用栈中查找，直到找到能够处理该类型异常的对象，这一过程称为**` 捕获（catch）异常 `.

**Java 异常强制用户考虑程序的强健性和安全性。异常处理不应用来控制程序的正常流程，其主要作用是捕获程序在运行时发生的异常并进行相应处理**编写代码处理某个方法可能出现的异常，可遵循如下三个原则：

1. 在当前方法声明中使用try catch语句捕获异常。
2. 一个方法被覆盖时，覆盖它的方法必须抛出相同的异常或异常的子类。
3. 如果父类抛出多个异常，则覆盖方法必须抛出那些异常的一个子集，而不能抛出新的异常。

## 三、异常类型

在Java中所有异常类型都是内置类 java.lang.Throwable 类的子类，即Throwable位于异常类层次结构的顶层。 Throwable  类下有两个异常分支` Exception  `和` Error `。

![1654821671230](\images\Java\Java-76.png)

由图可知Throwable类是所有异常和错误的超类，下面有Error和Exception两个子类分别表示错误和异常。其中异常类Exception又分为**运行时异常和非运行时异常**，这两种异常有很大的区别，也称为**不检查异常 （Unchecked Exception） 和检查异常 （Checked Exception）。**

- Exception类用于用户程序可能出现的异常情况，它也是用来创建自定义异常类型类的类。
- Error定义了在通常环境下不希望被程序捕获的异常。Error类型的异常用于Java运行时由系统显示与运行时环境系统本身有关的错误。堆栈溢出是这种错误的一例 。

**运行时异常**都是 RuntimeException 类及其子类异常，如 NullPointerException、IndexOutOfBoundsException 等，**这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理**。这些异常一般由程序逻辑错误引起，程序应该从逻辑角度尽可能避免这类异常的发生。

- Java中常见运行时异常

![1654822353775](\images\Java\Java-77.png)

**非运行时异常**是指 RuntimeException 以外的异常，类型上都属于 Exception 类及其子类。从程序语法角度讲是必须进行处理的异常，如果不处理，程序就不能编译通过。如 IOException、ClassNotFoundException 等以及用户自定义的 Exception 异常（一般情况下不自定义检查异常）。

-  Java常见非运行时异常

![1654822517167](\images\Java\Java-78.png)

## 四、try catch语句

Java的异常通过5个关键字来实现：try、catch、throw、throws和finally。**try catch语句用于捕获并处理异常，finally语句用于在任何情况下（除特殊情况下）都必须执行的代码，throw语句用于抛出异常，throws语句用于声明可能会出现的异常。**

try catch语句语法格式如下

```java
try{
	//可能发生异常的语句;
}catch(ExceptionType  e){
	//处理异常语句
}
```

在以上语法中，把可能引发异常的语句封装在try语句块中，用以捕获可能发生的异常。catch后的`（）`里放匹配的异常类，指明catch语句可以处理的异常类型，发生异常时产生异常类的实例化对象。

如果 try 语句块中发生异常，那么一个相应的异常对象就会被拋出，然后 catch 语句就会依据所拋出异常对象的类型进行捕获，并处理。处理之后，程序会跳过 try 语句块中剩余的语句，转到 catch 语句块后面的第一条语句开始执行。

如果 try 语句块中没有异常发生，那么 try 块正常结束，后面的 catch 语句块被跳过，程序将从 catch 语句块后的第一条语句开始执行。

::: tip 注意

try...catch 与 if...else 不一样 ,**try 后面的花括号`{}`不可以省略**，即使try块里只有一行代码，也不可以省略这个花括号。一直类似的是，**catch块后的花括号{}也不可以省略**。另外try块里声明的变量只是代码块内的局部变量，它只在try块内有效，其它地方不能访问该变量。

:::

在上面语法的处理代码块 1 中，可以使用以下 3 个方法输出相应的异常信息。

- printStackTrace() 方法：指出异常的类型、性质、栈层次及出现在程序中的位置。
- getMessage() 方法：输出错误的性质。
- toString() 方法：给出异常的类型与性质。

**案例**

编写一个录入学生姓名、年龄和性别的程序，要求能捕捉年龄不为数字时的异常。在这里使用 try catch 语句来实现，具体代码如下：

```java
public class ExceptionTest01 {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("---------学生信息录入---------------");
        String name = "";   // 获取学生姓名
        int age = 0;        // 获取学生年龄
        String sex = "";    // 获取学生性别
        try {
            System.out.println("请输入学生姓名");
            name = scanner.next();
            System.out.println("获取学生年龄");
            age = scanner.nextInt();
            System.out.println("获取学生性别");
            sex = scanner.next();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("输入有误！");
        }
        System.out.println("姓名：" + name);
        System.out.println("年龄：" + age);
        System.out.println("性别：" + sex);
    }
}
```

上述代码在 main() 方法中使用 try catch 语句来捕获异常，将可能发生异常的`age = scanner.nextlnt();`代码放在了 try 块中，在 catch 语句中指定捕获的异常类型为 Exception，并调用异常对象的 printStackTrace() 方法输出异常信息。运行结果如下所示。

![1654829123043](\images\Java\Java-79.png)

## 五、try catch finally语句

在实际开发中，根据 try catch 语句的执行过程，try 语句块和 catch 语句块有可能不被完全执行，而有些处理代码则要求必须执行。例如，程序在 try 块里打开了一些物理资源（如数据库连接、网络连接和磁盘文件等），这些物理资源都必须显式回收。
所以为了确保一定能回收 try 块中打开的物理资源，异常处理机制提供了 finally 代码块，并且 Java 7 之后提供了）技术。

finally 语句可以try catch 语句块匹配使用，语法格式如下：

```java
try {
    // 可能会发生异常的语句
} catch(ExceptionType e) {
    // 处理异常语句
} finally {
    // 清理代码块
}
```

对于以上格式，无论是否发生异常（除特殊情况外），finally 语句块中的代码都会被执行。此外，finally 语句也可以和 try 语句匹配使用，其语法格式如下：

```java
try {
    // 逻辑代码块
} finally {
    // 清理代码块
}
```

::: tip  使用 try-catch-finally 语句时需注意以下几点

1. 异常处理语法结构中只有 try 块是必需的，也就是说，如果没有 try 块，则不能有后面的 catch 块和 finally 块；
2. catch 块和 finally 块都是可选的，但 catch 块和 finally 块至少出现其中之一，也可以同时出现；
3. 可以有多个 catch 块，捕获父类异常的 catch 块必须位于捕获子类异常的后面；
4. 不能只有 try 块，既没有 catch 块，也没有 finally 块；
5. 多个 catch 块必须位于 try 块之后，finally 块必须位于所有的 catch 块之后。
6. finally 与 try 语句块匹配的语法格式，此种情况会导致异常丢失，所以不常见。

:::

**一般情况下，无论是否有异常拋出，都会执行 finally 语句块中的语句**，执行流程如图 1 所示。

![未命名文件 (\images\Java\Java-80.png)](C:\Users\杨洲\Downloads\未命名文件 (1).png)

::: info try catch finally 语句块的执行情况可以细分为以下 3 种情况

1. 如果 try 代码块中没有拋出异常，则执行完 try 代码块之后直接执行 finally 代码块，然后执行 try catch finally 语句块之后的语句。
2. 如果 try 代码块中拋出异常，并被 catch 子句捕捉，那么在拋出异常的地方终止 try 代码块的执行，转而执行相匹配的 catch 代码块，之后执行 finally 代码块。如果 finally 代码块中没有拋出异常，则继续执行 try catch finally 语句块之后的语句；如果 finally 代码块中拋出异常，则把该异常传递给该方法的调用者。
3. 如果 try 代码块中拋出的异常没有被任何 catch 子句捕捉到，那么将直接执行 finally 代码块中的语句，并把该异常传递给该方法的调用者。

:::

除非在 try 块、catch 块中调用了退出虚拟机的方法`System.exit(int status)`，否则不管在 try 块或者 catch 块中执行怎样的代码，出现怎样的情况，异常处理的 finally 块总会执行。

**案例**

当 Windows 系统启动之后，即使不作任何操作，在关机时都会显示“谢谢使用”。下面编写 Java 程序使用 try catch finally 语句这个过程，具体代码如下：

```java
public class ExceptionTest02 {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        System.out.println("Windows 系统已经启动");
        String[] pros = {"记事本","计算器","浏览器"};
        try {
            // 循环输出pros数组中的元素
            for (int i = 0;i<pros.length;i++){
                System.out.println(i+1+":"+pros[i]);
            }
            System.out.println("是否运行程序");
            String answer = input.next();
            if (answer.equals("y")){
                System.out.println("请输入程序编号");
                int number = input.nextInt();
                System.out.println("在运行程序["+pros[number-1]+"]");
            }else {
                System.out.println("输入错误，请重新输入");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally {
            System.out.println("谢谢使用!");
        }
    }
}
```

上述代码在 main() 方法中使用 try catch finally 语句模拟了系统的使用过程。当系统启动之后显示提示语，无论是否运行了程序，或者在运行程序时出现了意外，程序都将执行 finally 块中的语句，即显示“谢谢使用！”。输出时的结果如下所示。

![1654829372484](\images\Java\Java-81.png)

## 六、throws和throw：声明和抛出异常

Java中的异常处理除了捕获异常和处理异常之外，还包括声明异常和抛出异常。实现声明和抛出异常的关键字非常相似，它们是`throws和throw`。**可以通过throws关键字在方法上声明该方法要抛出的异常**，然后**在方法内部通过throw抛出异常对象**。

### 6.1、throws 声明异常

当一个方法产生一个它不处理的异常时，那么就需要在该方法的头部声明这个异常，以便将该异常传递到方法的外部进行处理。 使用 throws 声明的方法表示此方法不处理异常。throws 具体格式如下：

```java
returnType method_name(paramList) throws Exception 1,Exception2,…{…}
```

其中，returnType表示返回值类型；method_name表示方法名；paramList表示参数列表；Exception1.Exception2，....表示异常类。

**如果有多个异常类，它们之间用逗号分隔。** 这些异常类可以是方法中调用了可能拋出异常的方法而产生的异常，也可以是方法体中生成并拋出的异常。

使用throws声明抛出异常的思路是：当前方法不知道如何处理这种类型的异常，该异常应该由向上一级的调用者处理；如果main方法也不知道如何处理这种类型的异常，也可以使用throws声明抛出异常，该异常将交给JVM处理。JVM对异常的处理方法是：**打印异常的跟踪栈信息，并终止程序运行。**

### 6.2、throw 拋出异常

与 throws 不同的是，**throw 语句用来直接拋出一个异常，**后接一个可拋出的异常类对象，其语法格式如下：

```javascript
throw ExceptionObject;
```

其中，ExceptionObject 必须是 Throwable 类或其子类的对象。如果是自定义异常类，也必须是 Throwable 的直接或间接子类。例如，以下语句在编译时将会产生语法错误：

```java
throw new String("拋出异常");    // String类不是Throwable类的子类
```


当 throw 语句执行时，它后面的语句将不执行，此时程序转向调用者程序，寻找与之相匹配的 catch 语句，执行相应的异常处理程序。如果没有找到相匹配的 catch 语句，则再转向上一层的调用程序。这样逐层向上，直到最外层的异常处理程序终止程序并打印出调用栈情况。

throw 关键字不会单独使用，它的使用完全符合异常的处理机制，但是，一般来讲用户都在避免异常的产生，所以不会手工抛出一个新的异常类的实例，而往往会抛出程序中已经产生的异常类的实例。

**案例**

在某仓库管理系统中，要求管理员的用户名需要由 8 位以上的字母或者数字组成，不能含有其他的字符。当长度在 8 位以下时拋出异常，并显示异常信息；当字符含有非字母或者数字时，同样拋出异常，显示异常信息。代码如下：

```java
public class ExceptionTest03 {
    public boolean validateUserName(String username){
        boolean con = false;
        if (username.length() > 8){
            //判断用户长度是否大于8位
            for (int i = 0;i<username.length();i++){
                char ch = username.charAt(i);//获取每一个字符
                if ((ch > '0' && ch <= '9')|| (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z')){
                    con = true;
                }else {
                    con = false;
                    throw new IllegalArgumentException("用户名只能由字母和数字组成！");
                }
            }
        }
        else{
            throw new IllegalArgumentException("用户名长度必须大于 8 位！");
        }
        return con;
    }

    public static void main(String[] args) {
        ExceptionTest03 e3 = new ExceptionTest03();
        Scanner input = new Scanner(System.in);
        System.out.println("请输入用户名");
        String username = input.next();
        try {
            boolean con = e3.validateUserName(username);
            if (con){
                System.out.println("用户名输入正确");
            }
        } catch (IllegalArgumentException e) {
            System.out.println(e);
        }
    }
}
```

如上述代码，在 validateUserName() 方法中两处拋出了 IllegalArgumentException 异常，即当用户名字符含有非字母或者数字以及长度不够 8 位时。在 main() 方法中，调用了 validateUserName() 方法，并使用 catch 语句捕获该方法可能拋出的异常。

运行程序，当用户输入的用户名包含非字母或者数字的字符时，程序输出异常信息，如下所示。

![1654832006641](\images\Java\Java-82.png)

::: tip  throws 关键字和 throw 关键字在使用上的几点区别如下

- throws用来声明一个方法可能抛出的所有异常信息，表示出现一场的一种可能性，但并不一定会发生这些异常；throw则是指抛出一个具体的异常类型，执行throw则一定抛出了某种异常对象。
- 通过在一个方法（类）的声明处通过throws声明方法（类）可能抛出的异常信息，而在方法（类）内部通过throw声明一个具体的异常信息。
- throws通常不用显示地捕获信息，可由系统自动将所有捕获的异常信息抛给上级方法；throw则需要用户自己捕获相关的异常，而后在对其进行相关包装，最后将包装后的异常信息抛出。

:::

## 七、自定义异常

如果Java提供的内置异常类型不能满足程序设计的需求，这时我们可以**自己设计 Java 类库或框架**，其中包括异常类型。**实现自定义异常类需要继承 Exception 类或其子类**，如果自定义运行时异常类需继承 RuntimeException 类或其子类。

自定义异常的语法格式为：

```java
<class><自定义异常名><extends><Exception>
```

在编码规范上，一般将自定义异常类的类名命名为 XXXException，其中 XXX 用来代表该异常的作用。

**自定义异常类一般包含两个构造方法：一个是无参的默认构造方法，另一个构造方法以字符串的形式接收一个定制的异常消息，并将该消息传递给超类的构造方法。**

例如，以下代码创建一个名称为 IntegerRangeException 的自定义异常类：

```java
class IntegerRangeException extends Exception{
	public IntegerRangeException(){
		super();
	}
	public IntegerRangeException(String s){
		super(s);
	}
}
```

以上代码创建的自定义异常类IntegerRangeException类继承自Exception类，在该类中包含两个构造方法。

案例

编写一个程序，对会员注册的年龄进行验证，即检测是否在0~100岁。

1）这里创建一个异常类MyException，并提供两个构造方法。MyException类的实现代码如下：

```java
    public class MyException extends Exception{
	public MyException(){
		super();
	}
	public MyException(String str){
		super(str)
	}
}
```

2）接着创建测试类，调用自定义异常类。代码实现如下：

```java
public class Test {
    public static void main(String[] args) {
        int age;
        Scanner input = new Scanner(System.in);
        System.out.println("请输入您的年龄");
        try {
            age = input.nextInt();      //获取年龄
            if (age<0){
                throw new MyException("您输入的年龄有误，请重新输入");
            } else if (age>100) {
                throw new MyException("您输入的年龄大于100，请重新输入");
            }else {
                throw new MyException("您的年龄为:"+age);
            }
        } catch (InputMismatchException e1) {
            System.out.println("输入的不是数字");
        }catch (MyException e2){
            System.out.println(e2.getMessage());
        }
    }
}
```

3）运行该程序，当用户输入的年龄为负数时，则拋出 MyException 自定义异常，执行第二个 catch 语句块中的代码，打印出异常信息。程序的运行结果如下所示。

![1654839469704](\images\Java\Java-83.png)

当用户输入的年龄大于 100 时，也会拋出 MyException 自定义异常，同样会执行第二个 catch 语句块中的代码，打印出异常信息，如下所示。

![1654839522589](\images\Java\Java-84.png)

在该程序的主方法中，使用了 if…else if…else 语句结构判断用户输入的年龄是否为负数和大于 100 的数，如果是，则拋出自定义异常 MyException，调用自定义异常类 MyException 中的含有一个 String 类型的构造方法。在 catch 语句块中捕获该异常，并调用 getMessage() 方法输出异常信息。

::: tip 提示

因为自定义异常继承自 Exception 类，因此自定义异常类中包含父类所有的属性和方法。

:::
